---
apiVersion: v1
kind: Service
metadata:
  name: theaterservice
  labels:
    app: theaterservice
spec:
  type: NodePort
  selector:
    app: theaterservice
  ports:
    - protocol: TCP
      port: 9020
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theaterservice
spec:
  selector:
    matchLabels:
      app: theaterservice
  replicas: 1
  template:
    metadata:
      labels:
        app: theaterservice
    spec:
      containers:
        - name: theaterservice
          image: swati1109/moviebookingsystem:theatermanagementservice
          ports:
            - containerPort: 9010
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 30
            timeoutSeconds: 30