---
apiVersion: v1
kind: Service
metadata:
  name: movieservice
  labels:
    app: movieservice
spec:
  type: NodePort
  selector:
    app: movieservice
  ports:
    - protocol: TCP
      port: 9010
      name: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: movieservice
spec:
  selector:
    matchLabels:
      app: movieservice
  replicas: 1
  template:
    metadata:
      labels:
        app: movieservice
    spec:
      containers:
        - name: movieservice
          image: swati1109/moviebookingsystem:moviemanagementservice
          ports:
            - containerPort: 9010
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9010
            initialDelaySeconds: 30
            timeoutSeconds: 30